### ISSUE TITLE
WYSIWYG editor

### ISSUE THREAD

**Issue by jscancella** [USPTO/USPTO-DS-Theme#13]
At the bottom of https://uspto.github.io/USPTO-Design-System/components/formControls.html there is a WYSIWYG editor, but when our team is trying to test it, none of the buttons actually do anything. Is there a timeline for when this will be implemented? If not, what is the recommended editor to use while this is being built?

**Comment by scottmerker** [comment]
@jscancella - The editor control functionality is intended for demonstration of styling only, and you would be correct that the buttons do not do anything.  This was done intentionally to make the WYSIWYG editor agnostic of any plugins used to add that functionality.  We've had good luck using TinyMCE and many others, but it get's difficult to standardize on a single one, as technology stacks can be wildly different.  In the future, we are hoping to add a selection of WYSIWYG editor skin themes to match the Design System.  This is on our long-term roadmap.

**Comment by jscancella** [comment]
@scottmerker thanks for answering. Has the USPTO chosen a standard WYSIWYG (like TinyMCE)? I don't want to get into the position that the team uses something else and is forced to redo work if it can be avoided.
